version: '3.7'

services:

  qr_nginx:
    container_name: web
    build: ./docker/nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - staticfiles_dev_site:/var/www/html/static
      - media_dev_site:/var/www/html/media
    working_dir: /etc/nginx
    links:
      - qr_site
    networks:
      - dev
      

  qr_site:
    image: qr_site
    container_name: qr_site
    restart: unless-stopped
    build: 
      context: ./
      dockerfile: ./Dockerfile
    command: >
      bash -c "
        yes | python manage.py makemigrations --merge --noinput
        python manage.py migrate --noinput
        yes | python manage.py collectstatic --noinput
        gunicorn qrcode.wsgi:application --bind 0.0.0.0:8000
      "
    env_file:
      - ./.dev.env
    volumes:
      - staticfiles_dev_site:/usr/src/app/staticfiles
      - media_dev_site:/usr/src/app/media
    working_dir: /usr/src/app
    healthcheck:
      test: nc -z localhost 8000
    expose:
      - 8000
    networks:
      - dev
      
volumes:
  staticfiles_dev_site:
    driver: local
  media_dev_site:
    driver: local

networks:
  dev:
    external: true
